package uni.universityhalls;

public enum ROOM_TYPE {
    EMPTY,
    STUDENT_MALE,
    STUDENT_FEMALE,
    STUDENT_MIX,
    STUDENT_NONBINARY,
    EMPLOYEE_MALE,
    EMPLOYEE_FEMALE,
    EMPLOYEE_MIX,
    EMPLOYEE_NONBINARY

}
